theme: jekyll-theme-primer
markdown: CommonMarkGhPages
plugins:
  - jekyll-commonmark-ghpages
commonmark:
  options:
    - SMART
    - FOOTNOTES
  extensions:
    - autolink
    - strikethrough
    - table
    - tagfilter
